### ISSUE TITLE
getSwitchList error...

### ISSUE THREAD

**Issue by Franzens** [andig/homebridge-fritz#1]
Hello, Andy,

I have installed the module and get constantly the error: "getSwitchList error - retrying in 3 seconds"
My Fritzbox is Model 6490 with FRITZ!OS:06.50.

Homebridge is running with the homematic module stable since months - only the fritz module will not run. 
I tried difficult configs:
{
        "platform": "Fritz!Box",
        "name": "FRITZ!Box 6490 Cable (kdg)",
        "username": "Xxxxx",
        "password": "yyyyy",
        "url": "192.168.178.1",
        "interval": 120,
        "debug": false
    }

also

{
        "platform": "Fritz!Box",
        "name": "192.168.178.1",
        "username": "Xxxxx",
        "password": "yyyyy",
        "url": "192.168.178.1",
        "interval": 60,
        "debug": false
    }

where there lies my error?

**Comment by andig** [comment]
which version of smartfritz is installed? please check and try updating it.

**Comment by andig** [comment]
I've just pushed 0.2 that forces the updated smartfritz dependencies amongst other things.

**Comment by Franzens** [comment]
Oh. I have no smartfritz modul installed because i have no DECT200. I only wanted to control my guest wifi with the homebridge

Von unterwegs gesendet

**Comment by andig** [comment]
> I have no smartfritz modul installed 

You have if you use homebridge-fritz. Please upgrade to the current version. I'll close for now, please open new issue if problem persits.

**Comment by andig** [comment]
Repoening. This is a bug. Please make sure to specify "url" including the leading "http://". I'll fix this for the defaults.

**Comment by andig** [comment]
Fixed in 0.2.2.
