### ISSUE TITLE
Fritz DECT 200 nach Update verschwunden

### ISSUE THREAD

**Issue by michi692** [andig/homebridge-fritz#106]
Hallo,
nach einem Update des Plugin von 0.9.0 auf 0.9.2 erscheint zwar der FritzDECT 400-Schalter, dafür sind alle FritzDECT 200-Steckdosen aus der Homeübersicht verschwunden.
Nach einem Downgrade auf 0.9.0 muss ich die Steckdosen komplett neu konfigurieren (Benennung, Einbindung in Szenarien, etc.).

Die Logeinträge sind unauffällig, Steckdosen werden hier auch nach wie vor aufgelistet....

**Comment by jngmrks** [comment]
Ich bin auf der 0.9.1 und hab alle meine Steckdosen 5x 200 und 2x 210 drin.

**Comment by andig** [comment]
Duplicate of #109
