### ISSUE TITLE
getBatteryCharge is String, no INT

### ISSUE THREAD

**Issue by jngmrks** [andig/homebridge-fritz#11]
It seems that almost every Homekit App needs the battery charge as INT, but its delivered as String. No App works until i fixed it.

    this.platform.fritz('getBatteryCharge', this.ain).then(function(battery) {
        callback(null, parseInt(battery, 10));
    });

Quick and dirty ;)

Tested now multiply times, without the Fix i get always 0% Battery and an error.

**Comment by andig** [comment]
Will fix in upstream library.

**Comment by andig** [comment]
Fixed via https://github.com/andig/homebridge-fritz/commit/d2ff6ae5cecc1b0475d30d67c8063f724b9028b6
