### ISSUE TITLE
TemperatureSensor zentral abschalten

### ISSUE THREAD

**Issue by MikeDeltaHH** [andig/homebridge-fritz#114]
Moin!
Besteht die Möglichkeit das deaktivieren des TemperatureSensor als generelle Option zu setzen? Ich habe 11 DECT200 in meinem Setup und es kommt immer wieder mal vor dass die Sensoren nach Neustart der Homebridge in Homekit angezeigt werden obwohl ich sie dort einzeln ausgeblendet habe... jetzt jeden Stecker einzeln anzulegen um die Sensoren dann jeweils zu deaktivieren möchte ich gerne vermeiden...

**Comment by andig** [comment]
> obwohl ich sie dort einzeln ausgeblendet habe... 

Hast Du sie denn in der Konfiguration des Plugins ausgeschaltet?

**Comment by MikeDeltaHH** [comment]
Nein, ich habe die Anzeigt in der Eve App in Homekit einfach für jeden Stecker ausgeblendet, trotzdem wird mir dieses öfters mal nach Reboot der Homebridge dann angezeigt - nach einem erneuten Reboot ist die Anzeige wieder verschwunden... in Homebridge habe ich die Option eben nicht gesetzt da ich es so verstehe dass man dafür jedes Gerät einzeln eintragen und dort die Option abschalten muss und das ist mir bei der Vielzahl der DECT200 die ich im Einsatz habe etwas zuviel Aufwand... deshalb meine Frage ob die Möglichkeit besteht die Option zentral zu setzen dass sie für alle DECT200 oder generell alle Geräte gilt... hier ist meine config:

{
            "platform": "Fritz!Box",
            "name": "FritzBox 7590",
            "username": "xxx",
            "password": "xxx",
            "url": "http://fritz.box",
            "interval": 60,
            "concurrent": true,
            "wifiName": "xxx",
            "options": {
                "strictSSL": false
            }

**Comment by andig** [comment]
Schau bitte in die Readme! Dafür ist sie da ;)

**Comment by MikeDeltaHH** [comment]
Hm... ich steh grad auf dem Schlauch was Du meinst... die Readme habe ich mir zuerst angesehen bevor ich hier überflüssige Fragen poste aber da finde ich die Option nur pro Device und eben nicht zentral für alle...

**Comment by andig** [comment]
> aber da finde ich die Option nur pro Device und eben nicht zentral für alle...

Du meinst das Problem ist das einmalig für 11 Geräte mittels Copy/Paste in die Config einzutragen?

**Comment by MikeDeltaHH** [comment]
In der config die 11 Geräte anlegen, AIN aus der Fritzbox rauskopieren jeweils, etc... der Mensch ist von Natur aus faul... ;)... aber generell ist doch eine Option die man nur einmal setzen muss besser als eine die man x-mal setzt?! War ja eh nur die Frage ob das möglich wäre einzubauen...

**Comment by andig** [comment]
Möglich ist es sicher. Aber Du machst die Sache auch etwas komplizierter als sie sein muss. Die AINs gibt das Plugin dankbarerweise im Homebridge Log aus. Rauskopieren, mit gutem Texteditor (VSCode?) per Multi-Cursor aufsplitten und die Option in JSON formulieren, Copy/Paste und fertig. Sollte nicht länger als 5min dauern. Im Gegenzug mind. 1h programmieren und testen. Ich erlaube mir das als wontfix zu schließen, PR welcome ;)
