### ISSUE TITLE
BatteryCharge and StatusLowBattery is not updated on start

### ISSUE THREAD

**Issue by jngmrks** [andig/homebridge-fritz#12]
BatteryCharge and StatusLowBattery not updated on start. And not regular with the temperatur updates. Other Apps need to request the BatteryCharge to get it work in another App.

I think the best solution is to update the BatteryCharge and StatusLowBattery on start and on every temperatur update.

**Comment by andig** [comment]
Fixed via https://github.com/andig/homebridge-fritz/commit/a0fad76e9423cd5afdb3091ccb3818432b1c2078#diff-168726dbe96b3ce427e7fedce31bb0bcR578. Please retest.
