### ISSUE TITLE
Homebridge Version 1.0.0 funktioniert nicht

### ISSUE THREAD

**Issue by colseven** [andig/homebridge-fritz#123]
Hi,
mit Homebridge Version 1.0.0 funktioniert das Plugin leider nicht mehr.

**Comment by andig** [comment]
Fehlermeldung?

**Comment by colseven** [comment]
`
Apr 27 11:50:49 raspberrypi homebridge[2410]: [4/27/2020, 11:50:49] ERROR LOADING PLUGIN homebridge-fritz:
Apr 27 11:50:49 raspberrypi homebridge[2410]: [4/27/2020, 11:50:49] Error: Plugin /usr/local/lib/node_modules/homebridge-fritz requires a HomeBridge version of ^0.4.38 which does not satisfy the current HomeBridge version of 1.0.0. You may need to upgrade your installation of HomeBridge.
Apr 27 11:50:49 raspberrypi homebridge[2410]:     at Plugin.load (/usr/local/lib/node_modules/homebridge/src/plugin.ts:144:13)
Apr 27 11:50:49 raspberrypi homebridge[2410]:     at /usr/local/lib/node_modules/homebridge/src/pluginManager.ts:119:16
Apr 27 11:50:49 raspberrypi homebridge[2410]:     at Map.forEach (<anonymous>)
Apr 27 11:50:49 raspberrypi homebridge[2410]:     at PluginManager.initializeInstalledPlugins (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:117:18)
Apr 27 11:50:49 raspberrypi homebridge[2410]:     at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:148:24)
Apr 27 11:50:49 raspberrypi homebridge[2410]:     at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:74:10)
Apr 27 11:50:49 raspberrypi homebridge[2410]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Apr 27 11:50:49 raspberrypi homebridge[2410]:     at Module._compile (internal/modules/cjs/loader.js:1156:30)
Apr 27 11:50:49 raspberrypi homebridge[2410]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
Apr 27 11:50:49 raspberrypi homebridge[2410]:     at Module.load (internal/modules/cjs/loader.js:1000:32)
Apr 27 11:50:49 raspberrypi homebridge[2410]: [4/27/2020, 11:50:49] ====================
Apr 27 11:50:50 raspberrypi homebridge[2410]: [4/27/2020, 11:50:50] Loaded plugin: homebridge-neato
Apr 27 11:50:50 raspberrypi homebridge[2410]: [4/27/2020, 11:50:50] Registering platform 'homebridge-neato.NeatoVacuumRobot'
Apr 27 11:50:50 raspberrypi homebridge[2410]: [4/27/2020, 11:50:50] ---
Apr 27 11:50:51 raspberrypi homebridge[2410]: [4/27/2020, 11:50:51] Loaded plugin: homebridge-platform-blink-security
Apr 27 11:50:51 raspberrypi homebridge[2410]: homebridge API version: 2.5
Apr 27 11:50:51 raspberrypi homebridge[2410]: [4/27/2020, 11:50:51] Registering platform 'homebridge-platform-blink-security.BlinkSecurityPlatform'
Apr 27 11:50:51 raspberrypi homebridge[2410]: [4/27/2020, 11:50:51] ---
Apr 27 11:50:51 raspberrypi homebridge[2410]: [4/27/2020, 11:50:51] Loaded plugin: homebridge-tuya
Apr 27 11:50:51 raspberrypi homebridge[2410]: [4/27/2020, 11:50:51] Registering platform 'homebridge-tuya.TuyaLan'
Apr 27 11:50:51 raspberrypi homebridge[2410]: [4/27/2020, 11:50:51] ---
Apr 27 11:50:51 raspberrypi homebridge[2410]: [4/27/2020, 11:50:51] Loading 6 platforms...
Apr 27 11:50:51 raspberrypi homebridge[2410]: [4/27/2020, 11:50:51] [Config] Initializing config platform...
Apr 27 11:50:51 raspberrypi homebridge[2410]: [4/27/2020, 11:50:51] [Config] Spawning homebridge-config-ui-x with PID 2439
Apr 27 11:50:51 raspberrypi homebridge[2410]: [4/27/2020, 11:50:51] Error loading platform requested in your config.json at position 2
Apr 27 11:50:51 raspberrypi homebridge[2410]: [4/27/2020, 11:50:51] Error: The requested platform 'Fritz!Box' was not registered by any plugin.
Apr 27 11:50:51 raspberrypi homebridge[2410]:     at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:223:15)
Apr 27 11:50:51 raspberrypi homebridge[2410]:     at /usr/local/lib/node_modules/homebridge/src/server.ts:361:37
Apr 27 11:50:51 raspberrypi homebridge[2410]:     at Array.forEach (<anonymous>)
Apr 27 11:50:51 raspberrypi homebridge[2410]:     at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:348:27)
Apr 27 11:50:51 raspberrypi homebridge[2410]:     at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:151:29)
Apr 27 11:50:51 raspberrypi homebridge[2410]:     at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:74:10)
Apr 27 11:50:51 raspberrypi homebridge[2410]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Apr 27 11:50:51 raspberrypi homebridge[2410]:     at Module._compile (internal/modules/cjs/loader.js:1156:30)
Apr 27 11:50:51 raspberrypi homebridge[2410]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
Apr 27 11:50:51 raspberrypi homebridge[2410]:     at Module.load (internal/modules/cjs/loader.js:1000:32)
Apr 27 11:50:51 raspberrypi homebridge[2410]:     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
Apr 27 11:50:51 raspberrypi homebridge[2410]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
Apr 27 11:50:51 raspberrypi homebridge[2410]:     at internal/main/run_main_module.js:18:47
Apr 27 11:50:51 raspberrypi homebridge[2410]: [4/27/2020, 11:50:51] Got SIGTERM, shutting down Homebridge...
`

**Comment by andig** [comment]
See https://github.com/andig/homebridge-fritz/pull/122, just published 0.9.5.

**Comment by colseven** [comment]
Habe das Update auf die 0.9.5 gemacht, starten will er jedoch immer noch nicht.

`Apr 27 12:49:45 raspberrypi homebridge[1882]: [4/27/2020, 12:49:45] ERROR LOADING PLUGIN homebridge-fritz:
Apr 27 12:49:45 raspberrypi homebridge[1882]: [4/27/2020, 12:49:45] Error: Plugin /usr/local/lib/node_modules/homebridge-fritz requires a HomeBridge version of ^1.0.0 which does not satisfy the current HomeBridge version of 0.4.53. You may need to upgrade your installation of HomeBridge.
Apr 27 12:49:45 raspberrypi homebridge[1882]:     at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:57:11)
Apr 27 12:49:45 raspberrypi homebridge[1882]:     at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:153:14)
Apr 27 12:49:45 raspberrypi homebridge[1882]:     at Array.forEach (<anonymous>)
Apr 27 12:49:45 raspberrypi homebridge[1882]:     at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:145:22)
Apr 27 12:49:45 raspberrypi homebridge[1882]:     at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:57:24)
Apr 27 12:49:45 raspberrypi homebridge[1882]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:32:16)
Apr 27 12:49:45 raspberrypi homebridge[1882]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Apr 27 12:49:45 raspberrypi homebridge[1882]:     at Module._compile (internal/modules/cjs/loader.js:1156:30)
Apr 27 12:49:45 raspberrypi homebridge[1882]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
Apr 27 12:49:45 raspberrypi homebridge[1882]:     at Module.load (internal/modules/cjs/loader.js:1000:32)
Apr 27 12:49:45 raspberrypi homebridge[1882]: [4/27/2020, 12:49:45] ====================
Apr 27 12:49:45 raspberrypi homebridge[1882]: [4/27/2020, 12:49:45] Loaded plugin: homebridge-neato
Apr 27 12:49:45 raspberrypi homebridge[1882]: [4/27/2020, 12:49:45] Registering platform 'homebridge-neato.NeatoVacuumRobot'
Apr 27 12:49:45 raspberrypi homebridge[1882]: [4/27/2020, 12:49:45] ---
Apr 27 12:49:46 raspberrypi homebridge[1882]: [4/27/2020, 12:49:46] Loaded plugin: homebridge-platform-blink-security
Apr 27 12:49:46 raspberrypi homebridge[1882]: homebridge API version: 2.4
Apr 27 12:49:46 raspberrypi homebridge[1882]: [4/27/2020, 12:49:46] Registering platform 'homebridge-platform-blink-security.BlinkSecurityPlatform'
Apr 27 12:49:46 raspberrypi homebridge[1882]: [4/27/2020, 12:49:46] ---
Apr 27 12:49:46 raspberrypi homebridge[1882]: [4/27/2020, 12:49:46] Loaded plugin: homebridge-tuya
Apr 27 12:49:46 raspberrypi homebridge[1882]: [4/27/2020, 12:49:46] Registering platform 'homebridge-tuya-lan.TuyaLan'
Apr 27 12:49:46 raspberrypi homebridge[1882]: [4/27/2020, 12:49:46] ---
Apr 27 12:49:46 raspberrypi homebridge[1882]: [4/27/2020, 12:49:46] Loading 6 platforms...
Apr 27 12:49:46 raspberrypi homebridge[1882]: [4/27/2020, 12:49:46] [Config] Initializing config platform...
Apr 27 12:49:46 raspberrypi homebridge[1882]: [4/27/2020, 12:49:46] [Config] Spawning homebridge-config-ui-x with PID 1916
Apr 27 12:49:46 raspberrypi homebridge[1882]: [4/27/2020, 12:49:46] Error: The requested platform 'Fritz!Box' was not registered by any plugin.
Apr 27 12:49:46 raspberrypi homebridge[1882]:     at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
Apr 27 12:49:46 raspberrypi homebridge[1882]:     at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
Apr 27 12:49:46 raspberrypi homebridge[1882]:     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
Apr 27 12:49:46 raspberrypi homebridge[1882]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
Apr 27 12:49:46 raspberrypi homebridge[1882]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Apr 27 12:49:46 raspberrypi homebridge[1882]:     at Module._compile (internal/modules/cjs/loader.js:1156:30)
Apr 27 12:49:46 raspberrypi homebridge[1882]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
Apr 27 12:49:46 raspberrypi homebridge[1882]:     at Module.load (internal/modules/cjs/loader.js:1000:32)
Apr 27 12:49:46 raspberrypi homebridge[1882]:     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
Apr 27 12:49:46 raspberrypi homebridge[1882]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
Apr 27 12:49:46 raspberrypi homebridge[1882]:     at internal/main/run_main_module.js:18:47
Apr 27 12:49:46 raspberrypi homebridge[1882]: [4/27/2020, 12:49:46] Got SIGTERM, shutting down Homebridge...`

**Comment by andig** [comment]
Its all there:

> Error: Plugin /usr/local/lib/node_modules/homebridge-fritz requires a HomeBridge version of ^1.0.0 which does not satisfy the current HomeBridge version of 0.4.53. You may need to upgrade your installation of HomeBridge.

**Comment by colseven** [comment]
Sorry falschen code kopiert - das ist der Fehler
`Apr 27 12:59:06 raspberrypi homebridge[868]: [4/27/2020, 12:59:06] Error loading platform requested in your config.json at position 2
Apr 27 12:59:06 raspberrypi homebridge[868]: [4/27/2020, 12:59:06] Error: The requested platform 'Fritz!Box' was not registered by any plugin.
Apr 27 12:59:06 raspberrypi homebridge[868]:     at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:223:15)
Apr 27 12:59:06 raspberrypi homebridge[868]:     at /usr/local/lib/node_modules/homebridge/src/server.ts:361:37
Apr 27 12:59:06 raspberrypi homebridge[868]:     at Array.forEach (<anonymous>)
Apr 27 12:59:06 raspberrypi homebridge[868]:     at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:348:27)
Apr 27 12:59:06 raspberrypi homebridge[868]:     at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:151:29)
Apr 27 12:59:06 raspberrypi homebridge[868]:     at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:74:10)
Apr 27 12:59:06 raspberrypi homebridge[868]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Apr 27 12:59:06 raspberrypi homebridge[868]:     at Module._compile (internal/modules/cjs/loader.js:1156:30)
Apr 27 12:59:06 raspberrypi homebridge[868]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
Apr 27 12:59:06 raspberrypi homebridge[868]:     at Module.load (internal/modules/cjs/loader.js:1000:32)
Apr 27 12:59:06 raspberrypi homebridge[868]:     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
Apr 27 12:59:06 raspberrypi homebridge[868]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
Apr 27 12:59:06 raspberrypi homebridge[868]:     at internal/main/run_main_module.js:18:47
Apr 27 12:59:06 raspberrypi homebridge[868]: [4/27/2020, 12:59:06] Got SIGTERM, shutting down Homebridge...
`

**Comment by genfersee** [comment]
Same for me.

**Comment by colseven** [comment]
"platform": "Fritz!Box",
muss durch
"platform": "FRITZ!Box",
ersetzt werden, dann läuft es wieder

**Comment by genfersee** [comment]
Solved with this! Many thanks @colseven !

**Comment by andig** [comment]
See #124
