### ISSUE TITLE
Not working with Homebridge 1.0.1

### ISSUE THREAD

**Issue by StefanGebhardt** [andig/homebridge-fritz#125]
Since the update I have the problem, that the plugin (0.9.5) is not working.

Log
Error loading platform requested in your config.json at position 4
Apr 27 19:32:24 raspberrypi homebridge[18561]: [2020-4-27 19:32:24] Error: The requested platform 'Fritz!Box' was not registered by any plugin.
Apr 27 19:32:24 raspberrypi homebridge[18561]:     at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:223:15)
Apr 27 19:32:24 raspberrypi homebridge[18561]:     at /usr/local/lib/node_modules/homebridge/src/server.ts:361:37
Apr 27 19:32:24 raspberrypi homebridge[18561]:     at Array.forEach (<anonymous>)
Apr 27 19:32:24 raspberrypi homebridge[18561]:     at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:348:27)
Apr 27 19:32:24 raspberrypi homebridge[18561]:     at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:151:29)
Apr 27 19:32:24 raspberrypi homebridge[18561]:     at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:74:10)
Apr 27 19:32:24 raspberrypi homebridge[18561]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Apr 27 19:32:24 raspberrypi homebridge[18561]:     at Module._compile (internal/modules/cjs/loader.js:1156:30)
Apr 27 19:32:24 raspberrypi homebridge[18561]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
Apr 27 19:32:24 raspberrypi homebridge[18561]:     at Module.load (internal/modules/cjs/loader.js:1000:32)
Apr 27 19:32:24 raspberrypi homebridge[18561]:     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
Apr 27 19:32:24 raspberrypi homebridge[18561]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
Apr 27 19:32:24 raspberrypi homebridge[18561]:     at internal/main/run_main_module.js:18:47

CONFIG.JSON
     {
            "platform": "Fritz!Box",
            "name": "FritzBox",
            "username": "admin",
            "password": "xxxxxx",
            "url": "http://192.168.178.1",
            "interval": 300,
            "concurrent": false,
            "devices": {
                "wifi": {
                    "name": "Gäste WLAN",
                    "display": true
                },
                "outlet-1": {
                    "TemperatureSensor": false
                },
                "repeater-1": {
                    "TemperatureSensor": false
                },
                "thermostat-2": {
                    "ContactSensor": false
                },
                "hidden-3": {
                    "display": false
                }
            },
            "options": {
                "strictSSL": false
            }
        },

**Comment by StefanGebhardt** [comment]
Sorry, found it by myself:
"platform" has to be "FRITZ!Box"
No very user-friendly, this change :-)

**Comment by andig** [comment]
No, agreed. At this time though I can only follow through or revert. Could be too late for reverting now.
