### ISSUE TITLE
Still no acces with 0.9.5 on OZNU Docker Homebridge 1.0.1

### ISSUE THREAD

**Issue by frickler-at-home** [andig/homebridge-fritz#126]
Bei mit bleibt der beschriebene Fehler, trotz "platfom" = "FRITZ!Box" 
OZNU Docker Homebridge 1.0.1 mit Version 0.9.5 und egal mit welcher Config.json

**Comment by andig** [comment]
Welcher Fehler?

**Comment by frickler-at-home** [comment]
Ich habe 



in der config.json



den Teil "platform": "FRITZ!Box",



angepasst. Jedoch wird im LOG weiter der schon beschriebene Fehler angezeigt: " plugin no " etc.

Ich nutze HOMEBRIDGE Mittels Docker durch den Build von OZNU in der schon angegebenen Version



Das sieht so aus:



System Informationen
Zeitzone	GMT+0000
OS	Alpine Linux (3.10.3)
Hostname	oznu-homebridge
IPv4 (ovs_bond0)	172.30.100.xx
Node.js Version	v12.14.0
Npm Version	v6.13.4
Benutzer	root
Speicherpfad	/homebridge
Konfigurationspfad	/homebridge/config.json
Pluginpfad	/homebridge/node_modules
Docker	Yes



Ich habe die Heizungen der Fritzbox jetzt mittels FHEM eingebunden. Hilfreich ist das aber nicht!



Wie gesagt FRITZ ist als Grossschreibung in der config.json implementiert.

Der Fehler im Terminal bleibt bei den bisherigen Angaben.



Grüße F@h





-----Ursprüngliche Nachricht-----
Von: andig <notifications@github.com>
Gesendet: Montag 27 April 2020 21:32
An: andig/homebridge-fritz <homebridge-fritz@noreply.github.com>
CC: frickler-at-home <kilian@ge-sundheit.de>; Author <author@noreply.github.com>
Betreff: Re: [andig/homebridge-fritz] Still no acces with 0.9.5 on OZNU Docker Homebridge 1.0.1 (#126)


Welcher Fehler?

**Comment by andig** [comment]
> Welcher Fehler?

Welcher Fehler?

**Comment by frickler-at-home** [comment]
-----Ursprüngliche Nachricht-----
Von: andig <notifications@github.com>
Gesendet: Montag 27 April 2020 21:32
An: andig/homebridge-fritz <homebridge-fritz@noreply.github.com>
CC: frickler-at-home <kilian@ge-sundheit.de>; Author <author@noreply.github.com>
Betreff: Re: [andig/homebridge-fritz] Still no acces with 0.9.5 on OZNU Docker Homebridge 1.0.1 (#126)



Welcher Fehler?

—

Error: The requested platform 'FRITZ!Box' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:134:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:327:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11

**Comment by andig** [comment]
Bitte nochmal das ganze Logfile bis zum Fehler zeigen.

**Comment by f-io** [comment]
Wenn du es mit docker-compose machst:
root@homebridge: docker-compose stop && docker-compose up -d  && docker-compose logs -f
Und einfach den kompletten log kopieren. 

Hab das mit HB 1.0.2 (homebridge-fritz v0.9.5) und traefik 2.2.0 in docker getestet, und da kann ich das oben genannte Verhalten nicht reproduzieren. Vielleicht mal ein "docker-compose stop && docker-compose pull && docker-compose up -d --force-recreate  && docker-compose logs -f" testen.

**Comment by frickler-at-home** [comment]
Fehler behoben: Homebridge 1.0.2 läuft mit homebridge-fritz 0.9.5
Das Problem lag an unvermuteter Stelle: Der DockerContainer hatte eine fixe Umgebungsvariable die die Homebridge Version immer als 0.4.6 auswies, egal was real im Container lief.
Zeile aus dem Containerconfig entfernt. ----- Rennt!  Danke für die schnellen Antworten, sie haben geholfen
