### ISSUE TITLE
Verbindung zur Fritzbox nicht möglich unter FRITZ!OS: 07.19-77734 BETA

### ISSUE THREAD

**Issue by Cha0s80** [andig/homebridge-fritz#128]
Hallo,

ich habe schon seit längerem das Plugin genutzt und es hat alles tadellos funktioniert. Jetzt musste ich wegen eines Defektes die 7490 gegen eine 7590 mit der neuen Beta-Firmware tauschen. Nun funktioniert die Anmeldung an die Box scheinbar nicht. Ich bekomme folgende Meldung.
[2020-4-30 14:52:04] [My FRITZ!Box] Initializing FRITZ!Box platform accessories failed - wrong user credentials?
Danach hängt dich der Server auf. Lösche ich die Platform aus der Konfiguration läuft der Neustart durch.
Für einen Tipp wo ich den Fehler suchen muss wäre ich sehr dankbar.

**Comment by jngmrks** [comment]
Laut Fehlermeldung würde ich hier Username und Passwort prüfen. Ohne aktiver Benutzeranmeldung meine ich gelesen zu haben, dass der Username „root“ lauten muss.

Ich bin auf der gleichen BETA und es läuft wunderbar.

**Comment by Cha0s80** [comment]
Läuft wunderbar! Ich habe den Wald vor lauter Bäumen nicht gesehen. Habe aber einen Nutzer über den ich mich anmelden wollte, analog zur alten Box und der funktioniert auch. Das verstehe ich zwar nicht, aber Hauptsache es läuft. Danke!
