### ISSUE TITLE
Temperature-Sensors under 0° are not displayed

### ISSUE THREAD

**Issue by jngmrks** [andig/homebridge-fritz#13]
KhaosT writes: The current min/maxValue are generated from Apple's HomeKit Accessory Simulator.
KhaosT writes:  just do a  characteristic.props.minValue = targetMinValue  and it should work :)

**Comment by andig** [comment]
Mmhm- d.h. ich kann Apple sagen was es tun kann??? Mal was Neues- melde mic mit Update.

**Comment by jngmrks** [comment]
Sieht ganz so aus als würden sich diese Standard-Vorgaben überschreiben lassen. Machen wohl die anderen Homekit-Geräte auch so (Wetterstationen mit Aussensensor oder Wetterdienste)

**Comment by andig** [comment]
Closed via https://github.com/andig/homebridge-fritz/commit/e2dae22a081e30772bd391423da095c7a92d4674
