### ISSUE TITLE
Not working with Fritz OS 7.20

### ISSUE THREAD

**Issue by kpetrilli** [andig/homebridge-fritz#137]
As of the new FritzOS 7.20, this does not work any more. In fact, homebridge itself fails to start. I have a Fritx 7590 if this matters. Please consider updating

**Comment by beckerj** [comment]
Same setup here, and it works totally fine. (FB 7590, 7.20)

**Comment by kpetrilli** [comment]
Thank you for replying, will try re-install Home bridge from scratch and see if the problem persists then

**Comment by appliko** [comment]
It works pretty well to me

Thanks 

—
Tommaso Vercesi

**Comment by ronny332** [comment]
I'm on 7.20, too. The used fb7590 runs fine with homebridge-fritz, besides a longer existing issue, that switching devices often takes a long time (up to 20 seconds). But I think is related to the device itself.

**Comment by kpetrilli** [comment]
Solved: My problem was a duplicated of [This other issue](https://github.com/andig/homebridge-fritz/issues/124). 
I had to rename the platform name to uppercase in my config.json.
