### ISSUE TITLE
FRITZ!DECT 300 Support

### ISSUE THREAD

**Issue by creativecave** [andig/homebridge-fritz#19]
Hi,
i have 1 Comet DECT and some FRITZ!DECT 300s connected to my 7580.
Could you add support for the 300s? I can see temps but there is no way to set something.
If you need a device, i could send you one.

THX
Eugen

**Comment by andig** [comment]
Should alteady be possible. Which fritzos are you running?

**Comment by creativecave** [comment]
FRITZ!OS 6.81 on 7580

**Comment by andig** [comment]
> If you need a device, i could send you one.

@creativecave I have the comet dect, too- I assume this is working for you? If yes I'd appreciate a dect 300 which I don't have. Please pm me at cpuidle@gmx.de

**Comment by Aloha23L** [comment]
Same Issue here with Fritz DECT300. Temperature shown but no control.
Comet DECT works fine.
Fritz OS 06.80 on FritzBox 7390

**Comment by andig** [comment]
I'll check asap- waiting for a device now

**Comment by andig** [comment]
Could you share the homebridge debug output? I assume the dect300 does not appear in the list of thermostats found? Would you be able to run a quick diagnostic program using node from the fritzapi folder?

**Comment by Aloha23L** [comment]
I am sorry, but I am not familiar with this platform. I used the Homebridge app for setup. The debug log shows that the Fritz!DECT300 does not appear as a thermostat (I use 3 Comet DECT 1 Fritz!DECT300 and 1 Fritz!DECT200)
The ID 117950293256 of Fritz!DECT300 shows up as a sensor.

**Comment by andig** [comment]
Please try upgrading- should be fixed.

**Comment by Aloha23L** [comment]
Yes! Working fine now.
Thank You for fixing.

**Comment by andig** [comment]
Great :)
