### ISSUE TITLE
Homebridge is running - but not so that i can see her in EVE

### ISSUE THREAD

**Issue by Franzens** [andig/homebridge-fritz#2]
after installing the new version of the homebridge-fritz i cannot found some entries in the persist directory and the homebridge is not to find with eve.  The Homebridge logs in to the fritzbox. The raspi shows the following messages:

Jul 25 22:06:22 Raspi homebridge[1330]: [2016-07-25 22:06:22] [Fritz!Box] Fritz!Box platform login successful
Jul 25 22:06:24 Raspi homebridge[1330]: [2016-07-25 22:06:24] [Fritz!Box] Outlets found:
Jul 25 22:06:24 Raspi homebridge[1330]: Unhandled rejection TypeError: Cannot read property 'manufacturer' of undefined
Jul 25 22:06:24 Raspi homebridge[1330]: at new FritzOutletAccessory (/usr/local/lib/node_modules/homebridge-fritz/index.js:222:67)
Jul 25 22:06:24 Raspi homebridge[1330]: at /usr/local/lib/node_modules/homebridge-fritz/index.js:76:38
Jul 25 22:06:24 Raspi homebridge[1330]: at Array.forEach (native)
Jul 25 22:06:24 Raspi homebridge[1330]: at /usr/local/lib/node_modules/homebridge-fritz/index.js:75:22
Jul 25 22:06:24 Raspi homebridge[1330]: at tryCatcher (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/util.js:16:23)
Jul 25 22:06:24 Raspi homebridge[1330]: at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:504:31)
Jul 25 22:06:24 Raspi homebridge[1330]: at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:561:18)
Jul 25 22:06:24 Raspi homebridge[1330]: at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:606:10)
Jul 25 22:06:24 Raspi homebridge[1330]: at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:685:18)
Jul 25 22:06:24 Raspi homebridge[1330]: at Async._drainQueue (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/async.js:138:16)
Jul 25 22:06:24 Raspi homebridge[1330]: at Async._drainQueues (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/async.js:148:10)
Jul 25 22:06:24 Raspi homebridge[1330]: at Immediate.Async.drainQueues [as _onImmediate](/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/async.js:17:14)
Jul 25 22:06:24 Raspi homebridge[1330]: at processImmediate [as _immediateCallback](timers.js:383:17)
Jul 25 22:07:14 Raspi homebridge[1330]: [2016-07-25 22:07:14] [Fritz!Box] Updating guest WLAN

**Comment by andig** [comment]
> after installing the new version of the homebridge-fritz i cannot found some entries in the persist directory and the homebridge is not to find with eve. 

I must say that I have no idea what that means. Could you please set debug=true in the homebridge-fritz configuration and post the full output here?

**Comment by Franzens** [comment]
In which directory may i find the log?

Von unterwegs gesendet

**Comment by andig** [comment]
Right in the console if you don't start homebridge as service.

**Comment by Franzens** [comment]
2016-07-26 17:35 GMT+02:00 andig notifications@github.com:

**Comment by andig** [comment]
> 2016-07-26 17:35 GMT+02:00 andig notifications@github.com:

?

**Comment by Franzens** [comment]
? Means?

You got the log? 

Von unterwegs gesendet

**Comment by Franzens** [comment]
**Here the log from the last start homebridge with homematic, fritz and wunderground** 

Jul 26 20:57:36 Raspi node[24331]: *** WARNING *** Please fix your applicatio                                                                             n to use the native API of Avahi!
Jul 26 20:57:36 Raspi node[24331]: *** WARNING *** For more information see <                                                                             http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
Jul 26 20:57:36 Raspi node[24331]: *** WARNING *** The program 'node' called                                                                              'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
Jul 26 20:57:36 Raspi node[24331]: *** WARNING *** Please fix your application to use the native API of Avahi!
Jul 26 20:57:36 Raspi node[24331]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Jul 26 20:57:36 Raspi homebridge[24331]: *** WARNING *** Please fix your application to use the native API of Avahi!
Jul 26 20:57:36 Raspi homebridge[24331]: *** WARNING *** For more information  see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
Jul 26 20:57:36 Raspi homebridge[24331]: *** WARNING *** The program 'node' c                                                                             alled 'DNSServiceRegister()' which is not supported (or only supported partially                                                                             ) in the Apple Bonjour compatibility layer of Avahi.
Jul 26 20:57:36 Raspi homebridge[24331]: *** WARNING *** Please fix your application to use the native API of Avahi!
Jul 26 20:57:36 Raspi homebridge[24331]: *** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
Jul 26 20:57:42 Raspi homebridge[24331]: [2016-07-26 20:57:41] Loaded plugin:  homebridge-fritz
Jul 26 20:57:42 Raspi homebridge[24331]: [2016-07-26 20:57:42] Registering platform 'homebridge-fritz.Fritz!Box'
Jul 26 20:57:42 Raspi homebridge[24331]: [2016-07-26 20:57:42] ---
Jul 26 20:57:43 Raspi homebridge[24331]: [2016-07-26 20:57:43] Loaded plugin: homebridge-homematic
Jul 26 20:57:43 Raspi homebridge[24331]: [2016-07-26 20:57:43] Registering platform 'homebridge-homematic.HomeMatic'
Jul 26 20:57:43 Raspi homebridge[24331]: [2016-07-26 20:57:43] ---
Jul 26 20:57:45 Raspi homebridge[24331]: [2016-07-26 20:57:45] Loaded plugin: homebridge-wunderground
Jul 26 20:57:45 Raspi homebridge[24331]: [2016-07-26 20:57:45] Registering accessory 'homebridge-wunderground.WUNDERGROUND'
Jul 26 20:57:45 Raspi homebridge[24331]: [2016-07-26 20:57:45] ---
Jul 26 20:57:45 Raspi homebridge[24331]: [2016-07-26 20:57:45] Loaded config.json with 1 accessories and 2 platforms.
Jul 26 20:57:45 Raspi homebridge[24331]: [2016-07-26 20:57:45] ---
Jul 26 20:57:45 Raspi homebridge[24331]: [2016-07-26 20:57:45] Loading 2 platforms...
Jul 26 20:57:45 Raspi homebridge[24331]: [2016-07-26 20:57:45] [HomeMatic CCU] Initializing HomeMatic platform...
Jul 26 20:57:45 Raspi homebridge[24331]: [2016-07-26 20:57:45] [HomeMatic CCU] Homematic Plugin Version 0.0.30
Jul 26 20:57:45 Raspi homebridge[24331]: [2016-07-26 20:57:45] [HomeMatic CCU] Plugin by thkl  https://github.com/thkl
Jul 26 20:57:45 Raspi homebridge[24331]: [2016-07-26 20:57:45] [HomeMatic CCU] Homematic is a registered trademark of the EQ-3 AG
Jul 26 20:57:45 Raspi homebridge[24331]: [2016-07-26 20:57:45] [HomeMatic CCU] Please report any issues to https://github.com/thkl/homebridge-homematic/issues
Jul 26 20:57:45 Raspi homebridge[24331]: [2016-07-26 20:57:45] [HomeMatic CCU] init RPC
Jul 26 20:57:45 Raspi homebridge[24331]: [2016-07-26 20:57:45] [HomeMatic CCU] Local IP: 192.168.178.23
Jul 26 20:57:45 Raspi homebridge[24331]: [2016-07-26 20:57:45] [HomeMatic CCU] XML-RPC server for interface BidCos-RF.is listening on port 9090
Jul 26 20:57:45 Raspi homebridge[24331]: [2016-07-26 20:57:45] [HomeMatic CCU] Creating Local HTTP Client for CCU RPC Events
Jul 26 20:57:45 Raspi homebridge[24331]: [2016-07-26 20:57:45] [HomeMatic CCU] CCU RPC Init Call on port 2001 for interface BidCos-RF.
Jul 26 20:57:46 Raspi homebridge[24331]: [2016-07-26 20:57:46] [HomeMatic CCU] Fetching Homematic devices...
Jul 26 20:57:46 Raspi homebridge[24331]: [2016-07-26 20:57:46] [Fritz!Box] Initializing Fritz!Box platform...
Jul 26 20:57:46 Raspi homebridge[24331]: [2016-07-26 20:57:46] [Fritz!Box] Discovering accessories
Jul 26 20:57:46 Raspi homebridge[24331]: [2016-07-26 20:57:46] Loading 1 accessories...
Jul 26 20:57:46 Raspi homebridge[24331]: [2016-07-26 20:57:46] [Weather Underground] Initializing WUNDERGROUND accessory...
Jul 26 20:57:46 Raspi homebridge[24331]: [2016-07-26 20:57:46] [Fritz!Box] > getDeviceList (null)
Jul 26 20:57:46 Raspi homebridge[24331]: [2016-07-26 20:57:46] [HomeMatic CCU] Method call params for 'system.listMethods': homebridge
Jul 26 20:57:51 Raspi homebridge[24331]: [2016-07-26 20:57:51] [HomeMatic CCU] Channeltype WEATHER_RECEIVER not supported
Jul 26 20:57:51 Raspi homebridge[24331]: [2016-07-26 20:57:51] [HomeMatic CCU] Channeltype CLIMATECONTROL_RECEIVER not supported
Jul 26 20:57:52 Raspi homebridge[24331]: [2016-07-26 20:57:52] [HomeMatic CCU] Initializing platform accessory 'EG Bewegungsmelder Gang:1'...
Jul 26 20:57:52 Raspi homebridge[24331]: [2016-07-26 20:57:52] [HomeMatic CCU] Initializing platform accessory 'Bewegungsmelder Keller:1'...
Jul 26 20:57:52 Raspi homebridge[24331]: [2016-07-26 20:57:52] [HomeMatic CCU] Initializing platform accessory 'OG Bewegungsmelder Treppe:1'...
Jul 26 20:57:52 Raspi homebridge[24331]: [2016-07-26 20:57:52] [HomeMatic CCU] Initializing platform accessory 'Steckdosen Terrasse West:1'...
Jul 26 20:57:52 Raspi homebridge[24331]: [2016-07-26 20:57:52] [HomeMatic CCU] Initializing platform accessory 'Deko Türe WZ:1'...
Jul 26 20:57:52 Raspi homebridge[24331]: [2016-07-26 20:57:52] [HomeMatic CCU] Initializing platform accessory 'Dimmer Küche:1'...
…
Jul 26 20:57:53 Raspi homebridge[24331]: [2016-07-26 20:57:53] [HomeMatic CCU] NPM 0.0.30 vs Local 0.0.30
Jul 26 20:57:54 Raspi homebridge[24331]: [2016-07-26 20:57:54] [Fritz!Box] Fritz!Box platform login successful
Jul 26 20:57:54 Raspi homebridge[24331]: [2016-07-26 20:57:54] [Fritz!Box] > getDeviceList []
Jul 26 20:57:54 Raspi homebridge[24331]: [2016-07-26 20:57:54] [Fritz!Box] > getSwitchList ("be446391300462b4")
Jul 26 20:57:55 Raspi homebridge[24331]: [2016-07-26 20:57:55] [Fritz!Box] > getSwitchList [""]
Jul 26 20:57:55 Raspi homebridge[24331]: [2016-07-26 20:57:55] [Fritz!Box] Outlets found:
Jul 26 20:57:55 Raspi homebridge[24331]: Unhandled rejection TypeError: Cannot read property 'manufacturer' of undefined
Jul 26 20:57:55 Raspi homebridge[24331]: at new FritzOutletAccessory (/usr/local/lib/node_modules/homebridge-fritz/index.js:222:67)
Jul 26 20:57:55 Raspi homebridge[24331]: at /usr/local/lib/node_modules/homebridge-fritz/index.js:76:38
Jul 26 20:57:55 Raspi homebridge[24331]: at Array.forEach (native)
Jul 26 20:57:55 Raspi homebridge[24331]: at /usr/local/lib/node_modules/homebridge-fritz/index.js:75:22
Jul 26 20:57:55 Raspi homebridge[24331]: at tryCatcher (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/util.js:16:23)
Jul 26 20:57:55 Raspi homebridge[24331]: at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:504:31)
Jul 26 20:57:55 Raspi homebridge[24331]: at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:561:18)
Jul 26 20:57:55 Raspi homebridge[24331]: at Promise._fulfillPromises (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:660:14)
Jul 26 20:57:55 Raspi homebridge[24331]: at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/promise.js:686:18)
Jul 26 20:57:55 Raspi homebridge[24331]: at Async._drainQueue (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/async.js:138:16)
Jul 26 20:57:55 Raspi homebridge[24331]: at Async._drainQueues (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/async.js:148:10)
Jul 26 20:57:55 Raspi homebridge[24331]: at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-fritz/node_modules/bluebird/js/release/async.js:17:14)
Jul 26 20:57:55 Raspi homebridge[24331]: at processImmediate [as _immediateCallback] (timers.js:383:17)
Jul 26 20:58:46 Raspi homebridge[24331]: [2016-07-26 20:58:46] [Fritz!Box] Updating guest WLAN
Jul 26 20:58:46 Raspi homebridge[24331]: [2016-07-26 20:58:46] [Fritz!Box] > getGuestWlan ("be446391300462b4")
Jul 26 20:58:49 Raspi homebridge[24331]: [2016-07-26 20:58:49] [Fritz!Box] > getGuestWlan {"autoupdate":true,"activate_guest_access":false,"guest_ssid":"Jeckle Gast","wpa_key":"Kennwort","push_service":false,"group_access":true,"untrusted":false,"user_isolation":false,"down_time_activ":false,"disconnect_guest_access":false,"sec_mode":"3","down_time_value":"60"}
Jul 26 20:59:46 Raspi homebridge[24331]: [2016-07-26 20:59:46] [Fritz!Box] Updating guest WLAN
Jul 26 20:59:46 Raspi homebridge[24331]: [2016-07-26 20:59:46] [Fritz!Box] > getGuestWlan ("be446391300462b4")
Jul 26 20:59:49 Raspi homebridge[24331]: [2016-07-26 20:59:49] [Fritz!Box] > getGuestWlan {"autoupdate":true,"activate_guest_access":false,"guest_ssid":"Jeckle Gast","wpa_key":"Kennwort","push_service":false,"group_access":true,"untrusted":false,"user_isolation":false,"down_time_activ":false,"disconnect_guest_access":false,"sec_mode":"3","down_time_value":"60"}
Jul 26 21:00:46 Raspi homebridge[24331]: [2016-07-26 21:00:46] [Fritz!Box] Updating guest WLAN
Jul 26 21:00:46 Raspi homebridge[24331]: [2016-07-26 21:00:46] [Fritz!Box] > getGuestWlan ("be446391300462b4")
Jul 26 21:00:49 Raspi homebridge[24331]: [2016-07-26 21:00:49] [Fritz!Box] > getGuestWlan {"autoupdate":true,"activate_guest_access":false,"guest_ssid":"Jeckle Gast","wpa_key":"Kennwort","push_service":false,"group_access":true,"untrusted":false,"user_isolation":false,"down_time_activ":false,"disconnect_guest_access":false,"sec_mode":"3","down_time_value":"60"}
Jul 26 21:01:46 Raspi homebridge[24331]: [2016-07-26 21:01:46] [Fritz!Box] Updating guest WLAN
Jul 26 21:01:46 Raspi homebridge[24331]: [2016-07-26 21:01:46] [Fritz!Box] > getGuestWlan ("be446391300462b4")
Jul 26 21:01:49 Raspi homebridge[24331]: [2016-07-26 21:01:49] [Fritz!Box] > getGuestWlan {"autoupdate":true,"activate_guest_access":false,"guest_ssid":"Jeckle Gast","wpa_key":"Kennwort","push_service":false,"group_access":true,"untrusted":false,"user_isolation":false,"down_time_activ":false,"disconnect_guest_access":false,"sec_mode":"3","down_time_value":"60"}
Jul 26 21:02:46 Raspi homebridge[24331]: [2016-07-26 21:02:46] [Fritz!Box] Updating guest WLAN
Jul 26 21:02:46 Raspi homebridge[24331]: [2016-07-26 21:02:46] [Fritz!Box] > getGuestWlan ("be446391300462b4")
Jul 26 21:02:49 Raspi homebridge[24331]: [2016-07-26 21:02:49] [Fritz!Box] > getGuestWlan {"autoupdate":true,"activate_guest_access":false,"guest_ssid":"Jeckle Gast","wpa_key":"Kennwort","push_service":false,"group_access":true,"untrusted":false,"user_isolation":false,"down_time_activ":false,"disconnect_guest_access":false,"sec_mode":"3","down_time_value":"60"}
…. Its running and running

**Normally (Homebridge without fritz) ends the log alike the following – then i can find it in EVE:**

Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
Jul 25 22:23:14 Raspi homebridge[2065]:
Jul 25 22:23:14 Raspi homebridge[2065]:     ┌────────────┐
Jul 25 22:23:14 Raspi homebridge[2065]:     │ 031-45-154 │
Jul 25 22:23:14 Raspi homebridge[2065]:     └────────────┘
Jul 25 22:23:14 Raspi homebridge[2065]:
Jul 25 22:23:14 Raspi homebridge[2065]: [2016-07-25 22:23:14] Homebridge is running on port 51826.
Jul 25 22:23:15 Raspi homebridge[2065]: [2016-07-25 22:23:15] [HomeMatic CCU] NPM 0.0.30 vs Local 0.0.30

**Comment by andig** [comment]
I can see the problem:

```
Jul 26 20:57:54 Raspi homebridge[24331]: [2016-07-26 20:57:54] [Fritz!Box] > getSwitchList ("be446391300462b4")
Jul 26 20:57:55 Raspi homebridge[24331]: [2016-07-26 20:57:55] [Fritz!Box] > getSwitchList [""]
```

Instead of returning an empty array, the smartfritz library apparently returns an array with an empty element- which it shouldn't. 

Unfortunately I can't diagnose this in my setup as all types of switches and thermostats are attached. If you want this fixed I'd need the ability to connect to your FB (url, username, password) which you could send per PM. I understand thats asking a lot but the only troubleshooting I can offer right now.

**Comment by Franzens** [comment]
Ok thank you. i'll think about. Before i'll test to integrate the fb in my homematic. I hope i've time in the weekend.

Von unterwegs gesendet

**Comment by Franzens** [comment]
i´m successfully integrated the control of my guestwlan in the homematic
thank you for your help!

**Comment by andig** [comment]
> i´m successfully integrated the control of my guestwlan in the homematic
> thank you for your help!

So- what was the problem?

**Comment by Franzens** [comment]
I dont use the homebridge - i installed a Shell Skript from the homematic-Forum to control the Fritz-box
