### ISSUE TITLE
guest wlan failed

### ISSUE THREAD

**Issue by r32er** [andig/homebridge-fritz#20]
i got this error when i switch wifi:

`[2/19/2017, 7:31:06 PM] [My FritzBox] < setGuestWlan failed
Unhandled rejection setGuestWlan failed

Unhandled rejection setGuestWlan failed

`

**Comment by andig** [comment]
Whats your fritzOS version and language setting?

**Comment by r32er** [comment]
FRITZ!OS 06.06 and german setting

**Comment by andig** [comment]
See https://github.com/andig/fritzapi - you should be running 6.20 at least.

**Comment by r32er** [comment]
But when i check for update it is the newest version I got

**Comment by r32er** [comment]
I have a fritzbox 7270. maybe this not supports 6.20 and the fritz plugin?

**Comment by andig** [comment]
Maybe- I really don't know how the 7270/6.20 behaves. Nothing I could do, sorry....

**Comment by r32er** [comment]
its ok. my hardware seems to be too old ;)

**Comment by glumb** [comment]
I'm having the same issue with FritzOS 06.33
```
Jun 13 16:55:35 raspberrypi homebridge[2741]: [2018-6-13 16:55:35] [My FritzBox] Switching guest WLAN to true
Jun 13 16:55:36 raspberrypi homebridge[2741]: [2018-6-13 16:55:36] [My FritzBox] < setGuestWlan failed
Jun 13 16:55:36 raspberrypi homebridge[2741]: Unhandled rejection setGuestWlan failed
```
Retrieving the current WIFI status within homekit (when setting it in the fritzbox webinterface) works fine. I'm running the latest homebridge and homebridge-fritz plugin versions.

**Comment by andig** [comment]
I don't have a box of that version. I can only suggest to debug the respective FritzApi function and identify the differences compared to the fritzbox UI.
