### ISSUE TITLE
Enable/disable main wifi

### ISSUE THREAD

**Issue by vzlgdu** [andig/homebridge-fritz#28]
Hi, I would to know if it is possible implement to switch on/off the wlan as well as the guest wlan.

Thanks

**Comment by ghost** [comment]
Not possible as the fritz api doesnt support it. If avm will implement it i think we will get it working fast.

**Comment by andig** [comment]
> Not possible as the fritz api doesnt support it.

Actually, there's not guest wifi api either. I would be happy to accept a PR but it would need to rely on screen scraping.

**Comment by andig** [comment]
With resolution of https://github.com/andig/homebridge-fritz/issues/43 this should now be possible. 

Please let me know if still relevant.

**Comment by andig** [comment]
Seems solved.
