### ISSUE TITLE
Allow selectively disabling device characteristics

### ISSUE THREAD

**Issue by m4d-maNu** [andig/homebridge-fritz#31]
The Dect200 and 210 have a temperature sensor, can be hidden it in homebridge?

**Comment by andig** [comment]
Yes, see hidden option.

**Comment by m4d-maNu** [comment]
You mean with AIN the Serialnumber or?

Than my Dect 200 has the same Serialnumber in the plug function and in the temperature funtcion in Home.

**Comment by andig** [comment]
I see- you want to disable only the temperature sensor but not the switch? That's currently not implemented.

**Comment by m4d-maNu** [comment]
Can you intrigue it or is that not possible?

**Comment by andig** [comment]
Technically no problem and I‘d be happy to take a pr. Its not on my priority list though unless theres wider demand.

**Comment by martinB65** [comment]
+1
to disable the temperature sensor would be a great improvement for the plugin

**Comment by dominikconrads** [comment]
+1
to disable the temperature sensor would be a great improvement for the plugin

**Comment by andig** [comment]
See #42 for a suggestion how the configuration side of this request could look like.

**Comment by dominikconrads** [comment]
Besteht denn noch Hoffnung, dass dieser Feature-Request umgesetzt wird?
Ich schmeiße die Temeperatur-Sensor-Accessories immer aus der Favoriten-Ansicht, allerdings kommen diese immer wieder zurück...

**Comment by andig** [comment]
@dominikconrads es gibt so viele Projekte ;) Du kannst gerne mit einer kleinen Spende nachhelfen.

**Comment by dominikconrads** [comment]
@andig Ja klar, sag mir wie!

**Comment by andig** [comment]
In der Readme oben gibts einen Button (https://github.com/andig/homebridge-fritz/blob/master/README.md) oder direkt mit [PayPal](https://www.paypal.com/donate/?token=ovXjejGDOzswzwBYnHGFnpr0zb039hyYxOu7L5HYWxFLXdS2CRPJDIuW1ipsVxteSKLyTW&country.x=US&locale.x=US). Vielen Dank!

**Comment by andig** [comment]
Could you give https://github.com/andig/homebridge-fritz/pull/62 a shot?
