### ISSUE TITLE
getBatteryCharge failed @ Dect Comet

### ISSUE THREAD

**Issue by HuberDe** [andig/homebridge-fritz#35]
I'm just installed my first Comet thermostat and don't get the temperature. The logfile shows the following lines:

`[2017-12-28 08:47:08] [FritzBox] < getBatteryCharge failed
Unhandled rejection getBatteryCharge failed`

Thanks!

**Comment by andig** [comment]
Could you show a screenshot of your fritzbox ui that has the battery status?

**Comment by HuberDe** [comment]
![f824d579-1daa-4c86-a2a6-072be5a3d0be](https://user-images.githubusercontent.com/9192406/34406510-ce6e89c8-ebb9-11e7-985b-7bee61ee4497.jpeg)

**Comment by HuberDe** [comment]
I found the issue. It wasn't a plugin bug. My fritzbox user wasn't allowed to change Fritzbox settings, which is needed for screengrabbing the battery level. After enabling 

![bildschirmfoto 2017-12-28 um 11 39 51](https://user-images.githubusercontent.com/9192406/34408381-dc2c2bce-ebc3-11e7-8f6b-13a6b9a0f389.png)

for the user which homebridge-fritz is using to access the Fritzbox, all is working as expected. Thanks to Andreas for the quick support!

**Comment by andig** [comment]
It's actually in the readme:

	homebridge-fritz can login but not update thermostat battery charge

	Battery charge is not an API function. That means that the user must have access to FritzBox administration, not only to the SmartHome API in order to use this functionality. Update your Fritz!Box user accordingly.
