### ISSUE TITLE
Fritz!Powerline 530e

### ISSUE THREAD

**Issue by seydx** [andig/homebridge-fritz#37]
Hey everyone,

does this plugin support Fritz!Powerline 530e ?

**Comment by andig** [comment]
It should- have you tried?

Viele Grüße,
Andreas

**Comment by seydx** [comment]
No i am currently not at home :/ will test it later

**Comment by seydx** [comment]
Also ich habe es mal versucht, Plugin installiert und Gast Wlan Schalter wird mir angezeigt, jedoch keine Steckdosen...

Habe ein FritzBox 7430, muss man die Steckdosen unter dem Menü "Smart Home" über die Fritz Box Seite erstmal registrieren damit die vom Plugin entdeckt werden können?

Das Problem dann aber ist, bei mir scheint das mit der Suche nach "Fritz Box Aktoren" nicht zu funktioniert, wenn ich über Smart Home auf FritzBox nach neuen "Aktoren" suche, steht am Ende der Suche nur "Der Anmeldevorgang des FRITZ!-Aktors konnte nicht erfolgreich abgeschlossen werden."

Alles softwäremäßig aktuell... Jemand eine Idee?

Lg

**Comment by andig** [comment]
Du musst die Dosen erst an der FB anmelden. Bei Problemen damit bitte an den Avm Support wenden- kein Thema für homebridge-fritz.

**Comment by seydx** [comment]
Über den Menüpunkt 'Smart Home' auf der FritzBox Seite kriege ich nichts angemeldet :/
