### ISSUE TITLE
Missing HANFUN Window Contact in Homebridge and so in HomeKit

### ISSUE THREAD

**Issue by testpaul999** [andig/homebridge-fritz#38]
Hi, first thanks for the probertly working homebridge plugin.
At my Fritz!Box i have a window contact who works fine with a DECT200, if open ist colsed and if colsed the DECT200 is on.
at homebridge i only see this
[2018-2-16 09:26:00] [My FritzBox] Outlets found: 087610226897,087610229590,087610087090,087610079122,116570018303,087610079123,087610340529,087610208071,087610454568

the actor him self have this AIN
Modell HAN-FUN
Aktor Identifikationsnummer (AIN)11934 0107283

so you see the ANI is not visible.

can you fix this problem, pls?

regards
Jens

**Comment by testpaul999** [comment]
Guten Tag,

Ich schreibe meine Frage mal auf deutsch.
An meiner Fritz!Box habe ich einen FensterSensor von der Telekom am laufen.
Modell HAN-FUN
Aktor Identifikationsnummer (AIN)11934 0107283

Leider wird dieser nicht von dem Plugin für die Homebridge erkannt.
Er fehlt in dieser Liste.
[2018-2-16 09:26:00] [My FritzBox] Outlets found: 087610226897,087610229590,087610087090,087610079122,116570018303,087610079123,087610340529,087610208071,087610454568

Ist es Ihnen möglich die API so anzupassen, das auch solche HAN-Fünfzehn Sensoren erfasst werden?
Auf der Seite https://www.ip-phone-forum.de/forums/avm.361/ lassen sich eventuell Anregeungen finden.

Vielen Dank für Ihre Bemühungen.

Grüße
Jens

**Comment by andig** [comment]
Ich habe leider keinen entsprechenden Sensor zum testen. Bei entsprechendem Testgerät schaue ich mir das gerne an.

**Comment by testpaul999** [comment]
Hallo,

Danke für die Antwort.
Kann ich hier irgendwie helfen, oder benötigen Sie den Sensor persönlich?

Könnte mich hinreißen lassen einen zweiten zu besorgen und Ihnen leihweise zu überlassen.

Grüße

Jens-Uwe

Am 05.04.2018 um 09:49 schrieb andig <notifications@github.com<mailto:notifications@github.com>>:


Ich habe leider keinen entsprechenden Sensor zum testen. Bei entsprechendem Testgerät schaue ich mir das gerne an.

**Comment by andig** [comment]
Note to self (from https://forum.fhem.de/index.php?topic=76613.0):

	<device identifier="11324 0047082-1" id="2000" functionbitmask="8208" fwversion="0.0" manufacturer="0x2c3c" productname="HAN-FUN">
		<present>1</present>
		<name>Bewegungsmelder: Unit #0</name>
		<etsiunitinfo>
			<etsideviceid>406</etsideviceid>
			<unittype>515</unittype>
			<interfaces>32513,256</interfaces>
		</etsiunitinfo>
		<alert>
			<state>1</state>
		</alert>
	</device>

**Comment by andig** [comment]
Closed via 6896743ca48486db0cd7875e58fb14d6737bb28e
