### ISSUE TITLE
Doesn't use username and password

### ISSUE THREAD

**Issue by hardez** [andig/homebridge-fritz#4]
This plugin ignores the username and password field of the config. If you log the request you'll see that neither username nor password are send to the Fritzbox. So the plugin always complaining the wrong username/password

If you deactivate the authentication in the Fritzbox settings this plugin works quite nice. Could you please implement the authentication?!

**Comment by andig** [comment]
Could you share log and config? Here's where the login happens: https://github.com/andig/homebridge-fritz/blob/master/index.js#L138

**Comment by xtech86** [comment]
Hello,

myfritz box 7360 is password only so no username? Any ideas?

**Comment by hardez** [comment]
Sorry, already switched to pimatic, so all log files are gone. The pimatic version of the plugin works great.
