### ISSUE TITLE
Invert a contact sensor

### ISSUE THREAD

**Issue by ghost** [andig/homebridge-fritz#42]
Hi,
i have connected a QIVICON Door/Window contact vie DECT on the Smart Home section of my old FritzBox 7390. All works fine. I get a Message if the Status of the contact is changed. 
I want to use it as a marker if the  letterbox is no more empty. In the Apple Home App are only open and close to display (open or closed window...) not filled or empty. Unfortunately the text with the red sign means open if no letter will be in the box. For my usage I need the information in the status if the contact is closed.
Would it be possible to invert the status during the data collection from the FritzBox?
Thanks in advance
marslyric

(ich würde eine Möglichkeit benötigen, den Status zu invertieren)

**Comment by andig** [comment]
Straightforward to implement. We'd just need to `XOR` the state with an `invert` option.

However it would make more sense to globally cleanup the config options. Could look like this:

    {
      "platforms": [
        {
          "platform": "Fritz!Box",
          "name": "My Fritz!Box",
          "username": "",
          "password": "",
          "url": "http://fritz.box",
          "devices": {
            "guestwifi": {
              "name": "Guest WLAN"
            },
            "ain1": {
              "hidden": true
            },
            "alarmsensor ain2": {
              "invert": true
            },
            "dectrepeater ain3": {
              "disabled": [ "TemperatureSensor" ]
            }
          },
          "interval": 60,
          "debug": false
        }
      ]
    }

This should also include disabling characteristics as requested in https://github.com/andig/homebridge-fritz/issues/31

It's not too high on my priority list though but I'd be happy to accept a PR.

**Comment by marslyric** [comment]
Do you think it would be possible for you to implement the invert function?
What could I help for this?

**Comment by andig** [comment]
Shouldn‘t be too difficult. I‘m wondering though: do we need this as option or should the inverted behaviour the default? Opinions appreciated!

**Comment by marslyric** [comment]
With the HomeKit devices is no empty or full bag possible. With the door contact I have the tray picture if the contact is closed. The coloured picture is display if the contact is open. for my special usage as letterbox full, the contact is closed. That's why I wish to invert the behaviour. but it is special and the default is every time the door or window contact as describes above. The default should be not inverted in my opinion.

**Comment by andig** [comment]
Got iz. I will see what I can do over the next couple of days.

**Comment by andig** [comment]
Could you give https://github.com/andig/homebridge-fritz/pull/62 a shot?

**Comment by andig** [comment]
Fixed by #62
