### ISSUE TITLE
After change from FRITZ!Box 7490 to 7590 WLAN guest access switch doesn´t work

### ISSUE THREAD

**Issue by MikeDeltaHH** [andig/homebridge-fritz#43]
Hi!
I´ve changed this day my FRITZBox modell to 7590, restore my config and all works fine except the WLAN guest access switch - can see in the homebridge log:
 
[2018-4-30 21:06:33] [FritzBox 7590] Updating guest WLAN
[2018-4-30 21:06:33] [FritzBox 7590] Getting guest WLAN state
[2018-4-30 21:06:45] [FritzBox 7590] Switching guest WLAN to true

but nothing happens, the Guest WLAN isn´t going active...

Can´t find any error in my config.json, the configuration is exact the same i use with the 7490 and with this the plugin works fine and the switch turn on the Guest WLAN... any idea?

Regards!
Mike

Ich sehe grad dass Du deutsch schreibst... das macht es etwas einfacher, also nochmal... ich habe mir eine FRITZ!Box 7590 zugelegt, die Config meiner 7490 gesichert, zurückgespielt auf die 7590 und meine homebridge wieder hochgefahren, alles funktioniert soweit, alle Einstellungen wurden übernommen... nutze mit Deinem Plugin den Gast WLAN Switch und der funktioniert mit dem neuen Modell nicht mehr, an der config habe ich rein garnichts geändert! Zum Test mal den parameter "wifiName: "Guest WLAN" auf den Namen meines Gast-Netzes geändert den ich in der FRITZ!Box hinterlegt habe aber auch der wird augenscheinlich nicht übernommen, zumindest in den logs ist immer noch guest WLAN zu lesen... ich steuere auch drei FRITZ!DECT Stecker über Dein Plugin und das funktioniert problemlos...wenn ich das Gast WLAN über die FRITZ!Box einschalte wird es in HomeBridge trotzdem noch als "aus" angezeigt, augenscheinlich kann das Plugin den Status nicht auslesen, meldet aber trotzdem keinen Fehler...kannst Du mir helfen?

Viele Grüße!
Mike

**Comment by andig** [comment]
Mhhm. Bisher ging guest wlan immer. Bist Du sicher dass der User die entsprechenden Rechte hat? Debug log?

**Comment by MikeDeltaHH** [comment]
Hi!

Ja, in der config.json ist der admin der FRITZ!Box als User hinterlegt und die Steuerung der FRITZ!Dect Stecker klappt ja auch. In den logs finde ich nirgends einen Fehler, der Login wird als erfolgreich angezeigt und die Abfrage wird alle paar Sekunden durchgeführt...

2018-5-1 16:13:17] [FritzBox 7590] Updating guest WLAN
[2018-5-1 16:13:17] [FritzBox 7590] Getting guest WLAN state

Das einzige was ich mir als Ursache zusammenreimen kann ist dass seitens AVM etwas in der Firm geändert wurde die ich installiert habe - wegen Verbesserungen im Bereich WLAN & Radarerkennung habe ich die Labor Firm 06.98-55106 BETA laufen...

**Comment by andig** [comment]
Kannst Du das bitte nochmal mit einer Standardfirmware versuchen? Anscheinend gibt es ja mehr Unterschiede als nur das FB Modell?

**Comment by MikeDeltaHH** [comment]
Moin!
Die Firmware 6.98 Labor unterscheidet sich gegenüber der Version 6.93 der 7490 und der aktuellen 6.93 auf der 7590 nur dadurch dass da einige neue Features zuggekommen sind die nach Tests dann offiziell Standard werden, dabei sind einige Dinge die von der 7490 nicht unterstützt werden!
Ein Firmware Downgrade würde ich höchst ungerne vornehmen, beim Vorgängermodell ist mir dabei mal die ganze Konfiguration weggeflogen und mußte ich trotz Sicherung alles mögliche neu einrichten... im smartapfel Forum hat ein anderer Benutzer vom gleichen Problem berichtet, ich habe mal nachgehakt wleches Modell und Firm der einsetzt...

**Comment by MikeDeltaHH** [comment]
Der betreffende User im smartapfel Forum hat das Problem mit einer 7490 seit ca. 2 Wochen auch, gleiches Verhalten, mit normaler Firm & jetzt mit Laborfirm... wenn ich die hb im debugmode laufen lasse würdest Du da mehr verwertbare Infos bekommen hinsichtlich des Problems? die normalen Logs zeigen halt keine Fehler...

**Comment by andig** [comment]
Noch besser wäre den fritzapi Aufruf zu debuggen- leider muss der sich auf Screenscraping verlassen weil es von Avm keine offizielle Schnittstelle gibt 😩

**Comment by MikeDeltaHH** [comment]
Oha... wenn Du mir sagst wie das anzustellen ist...es wäre schon ziemlich klasse das plugin wieder zum laufen zu bekommen denn das Guest WLAN per Alexa ein- und auszuschalten hat einen gewissen Charme... :)

**Comment by MikeDeltaHH** [comment]
Nabend andig!
Es gibt ein neues plugin - homebridge-fritz-platform welches auch mit der neuen FRITZ!Box und der aktuellen Labor Firm läuft unf wo das Gast WLAN funktioniert, also ist dies generell möglich - leider ist das Gast WLAN in dem Plugin kein eigenständiges Gerät und kann ich somit nicht in Alexa ansprechen... gibt es vielleicht von Deinem Plugin noch eine neue Version mit Chance dass das wieder geht?

**Comment by andig** [comment]
Bin mir noch nicht ganz sicher, aber es scheint das TR64 API verwendet zu werden. Sollte möglich sein das ein zu bauen und stattdessen auf screen scraping zu verzichten. Gibts sonst Features aus dem anderen Plugin die Du vermissen würdest?

**Comment by andig** [comment]
@MikeDeltaHH schau mal bitte 0b3216b08256165b03b12174905b16dfc2fc0e6d an. Noch nicht released muss also per git installiert werden. Funktioniert aktuell *nur* aus dem internen Netz da der Port fest vorgegeben ist.

**Comment by MikeDeltaHH** [comment]
Nabend!
Die Möglichkeit die Box zu rebooten wäre auch nicht schlecht, sonst bin ich mit der Funktionalität der DECT Stecker superzufrieden und wenn das Gast WLAN wieder funktioniert wüßte ich grad nicht was man noch verbessern könnte... auf so Dinge wie AB oder Alarm kann ich persönlich verzichten!

[Edit]... hab´s grad installiert und funktioniert wieder, auch per Alexa - jetzt wird auch der WLAN Name und nicht mehr der generische "Guest WLAN" in HomeKit angezeigt, bin begeistert - vielen Dank dafür! :)

**Comment by andig** [comment]
Versuch mal:

    npm -i git://github.com/andig/homebridge-fritz#master <git://github.com/andig/homebridge-fritz#master> —save

Viele Grüße, Andreas

**Comment by MikeDeltaHH** [comment]
[Edit]... hab´s grad installiert und funktioniert wieder, auch per Alexa - jetzt wird auch der WLAN Name und nicht mehr der generische "Guest WLAN" in HomeKit angezeigt, bin begeistert - vielen Dank dafür! :)

**Comment by MikeDeltaHH** [comment]
Nachtrag... eine Anwesenheits-/Bewegungserkennung wie in dem anderen Plugin wäre klasse - das scheint besser zu funktionieren als das people plugin!

**Comment by andig** [comment]
Released as 0.7.1. Let's see what further feedback this will attract, especially regarding configurability.

**NOTE** Enabling guest Wifi will *only* work if it is otherwise completely configured in the FritzBox UI. E.g. if the WPA key is not configured the guest Wifi cannot be activated. Unfortunately the FritzBox Tr64 API does not return an error in this case.

> Anwesenheits-/Bewegungserkennung 

Da bin ich unsicher warum das in diesem Plugin notwendig ist und ob es nicht ein separates Plugin sein müsste? Bitte neues Issue für diese Diskussion aufmachen.
