### ISSUE TITLE
Gast-WLAN Abfrage laesst HomeBridge abstuerzen & funktioniert nicht mehr

### ISSUE THREAD

**Issue by MikeDeltaHH** [andig/homebridge-fritz#46]
Moin Andi!

Ich habe bei mir HomeBridge komplett neuinstalliert und die neue Version Deines plugins lässt HB immer wieder abstürzen, so ziemlich jede Stunde - allerdings nur die WLAN Abfrage, auf einem anderen Pi mit eigener HB Instanz werden nur die DECT!Stecker abgefragt und da gibt es keine Probleme - und leider funktioniert das aktivieren des Gast Zuganges auch nicht mehr, es passiert nichts, bzw. nach einer Weile meldet der Schalter einen Kommunikationsfehler und wenn ich das Gast WLAN über die FRITZ!Box aktiviere wird es trotzdem als "aus" angezeigt, die Funktion ist also komplett wieder weg... die Fehlermeldungen im HB Log:

[2018-6-24 09:13:40] [FritzBox 7590] Updating guest WLAN
[2018-6-24 09:13:40] [FritzBox 7590] Getting guest WLAN state
/usr/local/lib/node_modules/homebridge-fritz/node_modules/tr-064/lib/Service.js:253
            error = new Error("sendSOAPActionRequest Error: " + response.statusCode);
                                                                         ^
TypeError: Cannot read property 'statusCode' of undefined
    at Request._callback (/usr/local/lib/node_modules/homebridge-fritz/node_modules/tr-064/lib/Service.js:253:74)
    at self.callback (/usr/local/lib/node_modules/homebridge-fritz/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.onRequestError (/usr/local/lib/node_modules/homebridge-fritz/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:375:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
homebridge.service: Main process exited, code=exited, status=1/FAILURE
homebridge.service: Unit entered failed state.
homebridge.service: Failed with result 'exit-code'.
homebridge.service: Service hold-off time over, scheduling restart.
Stopped Node.js HomeKit Server.
Started Node.js HomeKit Server.

Gruß!
Michael

**Comment by andig** [comment]
I've replaced the underlying library. Bitte nochmal mit 0.7.2 versuchen. Anwesenheitserkennung kommt demnächst.

**Comment by MikeDeltaHH** [comment]
Vielen Dank für Deine prompte Hilfe, ich hab´s installiert und teste - wenn das mit der Bewegungserkennung auch noch was wird ist das ein Träumchen denn beim fritz-platform plugin was das auch unterstützt habe ich derbst mit Problemen zu kämpfen! :)

[Edit] Gast-WLAN Aktivierung funktioniert schon mal wieder, ich schaue mal bis morgen wie es mit den Abstürzen aussieht!

**Comment by maciboy** [comment]
Und ich wunder mich seit 2 Tagen, dass meine über Homebridge erstellten Geräte in den letzten Tagen häufig "Keine Antwort" zeigten ;)
Update auf 0.7.2 hab ich jetzt gemacht.
Allerdings bleibt das Problem, was mich gerade hergeführt hat, bestehen und zwar folgender Fehler:

Meine FritzBox 7490 ist unter fritz.box nicht erreichbar, wegen PiHole und DNS...
Deswegen habe ich in der Config dieses Plugins die IP (192.1.68.178.1) eingetragen.
Seit neustem kommt beim Starten allerdings dieser Fehler, weil das Plugin nicht auf meine URL achtet sondern scheinbar default-mäßig fritz.box öffnen will:

0.7.1:
![bildschirmfoto 2018-06-26 um 17 18 54](https://user-images.githubusercontent.com/19333006/41922913-739f4fe2-7966-11e8-9499-ebf131285b62.png)

0.7.2:
![bildschirmfoto 2018-06-26 um 17 31 18](https://user-images.githubusercontent.com/19333006/41923042-c82dc4bc-7966-11e8-9530-e7eb83f9b4ea.png)

Config:

"platforms": [
        {
            "platform": "Fritz!Box",
            "name": "FritzBox 7490",
            "username": "<username>",
            "password": "xxxxxxx",
            "url": "http://192.168.178.1",
            "interval": 86400,
            "wifiName": "GastLan",
            "options": {
                "strictSSL": true
            }
        },

Edit:
Ich vermute der Fehler liegt hier, weil der host hartgecoded ist:
https://github.com/andig/homebridge-fritz/blob/master/lib/accessories/wifi.js

else {
        this.platform.log("Using tr64 api for guest Wifi");

        var options = {
          **host: 'fritz.box',**
          port: 49000,
          ssl: false,
          user: this.platform.config.username,
          password: this.platform.config.password
        };

**Comment by andig** [comment]
Ahh, sorry. Habe gerade 0.7.3 gepusht. Damit geht allerdings immer noch kein Zugriff von draussen auf das Guest Wifi- dafür hab ich bisher keine gute Idee wie an den Port zu kommen ist.
