### ISSUE TITLE
Bug in wifi.js

### ISSUE THREAD

**Issue by tobiwashere** [andig/homebridge-fritz#47]
Erstmal danke für das Plugin und deine Arbeit! 👍 

Wenn der eingestellte Refreshintervall "zuschlägt" bekomme ich folgende Fehlermeldung:

> [7/16/2018, 10:05:17 PM] Homebridge is running on port 51826.
> [7/16/2018, 10:06:14 PM] [Fritz] Updating guest WLAN
> [7/16/2018, 10:06:14 PM] [Fritz] Getting guest WLAN state
> /usr/local/lib/node_modules/homebridge-fritz/lib/accessories/wifi.js:101
>     this.tr64service.actions.GetInfo().then((res) => {
>                      ^
> 
> TypeError: Cannot read property 'actions' of undefined
>     at FritzWifiAccessory.getOn (/usr/local/lib/node_modules/homebridge-fritz/lib/accessories/wifi.js:101:22)
>     at FritzWifiAccessory.update (/usr/local/lib/node_modules/homebridge-fritz/lib/accessories/wifi.js:163:5)
>     at ontimeout (timers.js:427:11)
>     at tryOnTimeout (timers.js:289:5)
>     at listOnTimeout (timers.js:252:5)
>     at Timer.processTimers (timers.js:212:10)

Ich habe eine FritzBox 6490 mit dem OS 6.87

hier meine config.json:

>    "platforms": [
>     {
>       "platform": "Fritz!Box",
>       "name": "Fritz",
>       "username": "",
>       "password": "XXX",
>       "url": "http://fritz.box",
>       "hide": [],
>       "interval": 60,
>       "wifiName": "GastWLAN",
>       "concurrent": false,
>       "debug": false
>     }
>   ]

Wenn ich unter "hide" "wifi" eintrage, kommt der Fehler nicht.

**Comment by andig** [comment]
Ibelieve this should be fixed by newer FritzOs. Closing.
