### ISSUE TITLE
Fritz!dect Switch status change kommt nicht bei Apple Home an.

### ISSUE THREAD

**Issue by ggiese2000** [andig/homebridge-fritz#54]
Moin moin.
Seit geraumer Zeit nutze ich einen Fritz!Dect 200 zur zentralen Steuerung und Messung meiner Klimaanlage.

Das funktioniert sehr gut, wenn auch der Verbrauch nur direkt an der Fritz!box ablesbar ist und nicht über Homebridge - schade eigentlich, wäre schön er tauchte als Sensor auf.

Jetzt wollte ich aber einen zweiten Stecker für die Waschmaschine einsetzen.
Die Idee: Sobald die Maschine fertig ist verbraucht sie keinen Strom mehr und der Stecker schaltet sich aus (einstellbares Verhalten des Steckers). Dieses Signal geht an meine Apple Automatisierung, die dann eine Hue-Lampe auf "grün" stellt.

**Leider musste ich feststellen, dass die Schaltzustands-Änderung nicht weiter gegeben wird, wenn sie ausserhalb von Apple Home stattfindet. :(.**

Daher meine Frage:
Kann ich irgendetwas tun, damit der Schaltzustand auch kommuniziert wird, wenn er nicht über Apple Home geändert wird sondern direkt?
Zwischen Hue und Apple geht das ja auch.

**Comment by andig** [comment]
Das sollte funktionieren. Alle 60s werden die Stecker via `getSwitchState` abgefragt. Wenn das bei Dir nicht der Fall ist bitte Logfile bereit stellen in dem der Ablauf nachvollziehbar ist.

**Comment by ggiese2000** [comment]
Moin noch mal und Danke für die schnelle Antwort.
Ich kann tatsächlich erkennen, dass homebridge den Wechsel erkennt:

```
[11/4/2018, 4:43:57 PM] [Fritz!Box] > getSwitchState ("2a894c8a07bf764e","087610105200")
[11/4/2018, 4:43:58 PM] [Fritz!Box] < getSwitchState true
[11/4/2018, 4:44:37 PM] [Fritz!Box] > getSwitchState ("2a894c8a07bf764e","087610105200")
[11/4/2018, 4:44:40 PM] [Fritz!Box] < getSwitchState false

```

Diese Änderung wird aber scheinbar an Homekit nicht weitergereicht, daher funktioniert die nachgeschaltete Automatik nicht, das ist also weniger ein Problem mit Deinem Code als mit Homebridge selber.
Zum Vergleich:
Die Hue bridge gibt jede Änderung unverzüglich weiter.

Gibt es einen Weg Homebridge dazu zu bringen, diese Info zu pushen?

Anbei noch ein Logfile. switch in Frage ist outlet 08761010XXXX.

[homebridge.txt](https://github.com/andig/homebridge-fritz/files/2546112/homebridge.txt)

**Comment by andig** [comment]
Reagiert denn nur homebridge nicht in der Automatisierung oder siehst Du die Schalteränderung selber nicht in der Home App? Siehst Du andere Updates, wie z.B. die Temperatur?

Welcher Versionen von fritzapi und homebridge-fritz hast Du installiert?

**Comment by ggiese2000** [comment]
Wenn ich die Home App starte sehe ich den aktuellen Schalterzustand korrekt - aber nur dann. Wenn ich also ca 30 Sekunden nach dem Einschalten die App starte funktioniert auch der eingestellte Automatismus. 
Allerdings wird der Zustand nicht an das HomeKit gepusht, ohne, dass ich die App starte.

**Comment by andig** [comment]
Sehr seltsam.

> Welcher Versionen von fritzapi und homebridge-fritz hast Du installiert?

**Comment by ggiese2000** [comment]
Homebridge: 0.4.33
NPM: 4.2.0
Node JS: 7.2.0
homebridge-fritz: 0.5.9

**Comment by andig** [comment]
Please upgrade to current version.

**Comment by ggiese2000** [comment]
Habe jetzt mal update gefahren
Homebridge: 0.4.33 - jetzt 0.4.5
NPM: 4.2.0 - jetzt 5.6.0
Node JS: 7.2.0 - jetzt 9.9.0
homebridge-fritz: 0.5.9 - jetzt 0.7.3

Alles Läuft und ich bin peinlich berührt - aber DANKE!!

**Comment by andig** [comment]
Ist doch bestens- den Schrott zwischendurch habe ich ja auch released 😂
