### ISSUE TITLE
Guest WLAN unauthorized 401

### ISSUE THREAD

**Issue by tobiwashere** [andig/homebridge-fritz#63]
FB Model: 6490
Firmware: 7.01 (kdg)

I just updated this plugin to version 0.8.0 and customized my config to the new parameters. As I wanted to control my guest Wifi the log only displayed a '401 - unauthorized'.
I'm using the option "only password" in FritzBox under security (no username). In the config I left empty like this`"username": "",` and I got the 401 error.
I played with some settings in FritzBox, but nothing helped. I solved this problem with setting the username parameter to some various value and restarted homebridge, now it's working. No error 401 anymore and the guest wifi switch in homekit works as expected.
Maybe you can add some info to the readme.md or send some default value, if this parameter is blank in the config.

**Comment by andig** [comment]
Thanks, updated the readme https://github.com/andig/homebridge-fritz/commit/e87e79c493d0db13df71720f61e9bfcdea598af2#diff-04c6e90faac2675aa89e2176d2eec7d8R108

**Comment by tobiwashere** [comment]
Well your text is not fully correct, you can use the option 'only password' under security in the FritzBox, but you have to give some random username in the homebridge config, even if this username doesn't exist in FritzBox or to be precise, if you use the 'only password' option. Only when leaving this parameter empty gives the 401 error.

**Comment by andig** [comment]
Please feel free to correct the wording- prs welcome!

**Comment by tobiwashere** [comment]
There you go: #64 :-)

**Comment by andig** [comment]
Great, thank you!
