### ISSUE TITLE
Nur ca 60% der Homekit-Automationen kommen durch

### ISSUE THREAD

**Issue by lath35** [andig/homebridge-fritz#65]
Hi,
ich habe das Problem, dass meine im Homekit aufgestellten Automationen nicht immer durchkommen. Am deutlichsten zeigt sich das bei Geofencing-Automationen.
Als Steuerzentrale nutze ich ein iPad (Apple Tv4 auch schon ausprobiert).
Alle Geräte sind korrekt aufgesetzt mit allen Einstellungen etc.
Meine Homebridge läuft auf einem raspberrypi, den ich nach folgender Anleitung aufgesetzt habe: https://smartapfel.de/homebridge/
Kann man sich die Logs in solcher Form ausgeben lassen, dass man sieht wo das Signal der Automationen "verschluckt" wird?

**Comment by andig** [comment]
Siehe readme für Debughinweise.

**Comment by lath35** [comment]
Die readme habe ich gelesen.
Wenn ich allerdings homebridge beende und mit "homebridge -D" neu starten möchte, bekomme ich folgenden Fehler:

Mai 09 10:22:33 raspberrypi homebridge[316]: [2019-5-9 10:22:33] Got SIGTERM, shutting down Homebridge...
Mai 09 10:22:33 raspberrypi systemd[1]: Stopping Node.js HomeKit Server...
Mai 09 10:22:38 raspberrypi systemd[1]: homebridge.service: Main process exited, code=exited, status=143/n/a
Mai 09 10:22:38 raspberrypi systemd[1]: Stopped Node.js HomeKit Server.
Mai 09 10:22:38 raspberrypi systemd[1]: homebridge.service: Unit entered failed state.
Mai 09 10:22:38 raspberrypi systemd[1]: homebridge.service: Failed with result 'exit-code'.

Ist das so gewollt?
Ich dachte in debug-modus müsste ich die homebridge auch nutzen können um die Sachen zu testen.

**Comment by andig** [comment]
Stopp bitte den homebridge service komplett und starte dann von Hand ohne systemd. 

Viele Grüße,
Andreas

**Comment by lath35** [comment]
Hi Andreas,

ich habe ein paar Sachen an meinem Wlan Netzwerk geändert und zur Zeit scheint es stabil zu laufen.
Ich habe es auch geschafft die Homebridge im Debug modus laufen zu lassen.
Da es aber seit über einer Woche funktioniert kannst du das Thema schliessen.

Vielen Dank für deine Hilfe
LG
Alex
