### ISSUE TITLE
Disable Logging

### ISSUE THREAD

**Issue by Bankaifan** [andig/homebridge-fritz#68]
Hi,

Is it possible to control the logging of the plugin? I don’t need the „getting guest wlan state“ messages in the log.
![5A940242-8B9B-49A6-98D7-993B8844A469](https://user-images.githubusercontent.com/476059/58006989-95296f00-7ae9-11e9-86af-c6af7b3b85ac.png)

**Comment by andig** [comment]
Are you running homebridge with debug logging enabled?

**Comment by Bankaifan** [comment]
Oh. Problem solved. Sorry and thank you!

Daniel Kaiser




Am Mo., 20. Mai 2019 um 13:13 Uhr schrieb andig <notifications@github.com>:

**Comment by andig** [comment]
PS.: ich hab mal Deine Telefonnummer rausgelöscht...

**Comment by genfersee** [comment]
Hello!
@andig, I am running Homebridge in non debug mode but I still get this guest WLAN logs. How can I desactivate these logs?
Thanks!
