### ISSUE TITLE
Fritz!Dect 100 Repeater

### ISSUE THREAD

**Issue by michis0806** [andig/homebridge-fritz#7]
Hi andig,

first of all: Thanks for your great work! I am very happy with the plugin which helps me very much!

But I have a question concerning the AVM Dect!100 repeaters. Unfortunately your plugin seems to ignore the repeater which also provides a temperature.

Is it possible to add these devices, too?

I played a bit with some AVM php frameworks. It seems that the Repeaters aren't listet with the getdevice function but I was able to get the temperature when I manually provided the AIN.  Maybe you could provide a additional parameter with an array of additionals AIN to check?

Thanks a lot
Michael

**Comment by andig** [comment]
Shouldnt be a problem but I'd need remote access to your fritzbox to test. If acceptable please pm me (cpuidle at gmx.de)

**Comment by andig** [comment]
Update: that would probably imply implementing the DECT100 as new accessory of type `FritzTemperaturSensor` as it does not provide any other services?

**Comment by andig** [comment]
Please test https://github.com/andig/homebridge-fritz/pull/9

**Comment by andig** [comment]
Closing due to missing feedback- this should be working now. If not please reopen this issue.
