### ISSUE TITLE
Fritz!DECT 400 Support

### ISSUE THREAD

**Issue by marslyric** [andig/homebridge-fritz#71]
Hi,
would it be possible to get Homebridge support for a Fritz!DECT 400 Button?

**Comment by andig** [comment]
I could try to do this, but I'm unsure this would work with the current Fritz API. As I need to poll the devices and the button is only pushed briefly I'm not sure how the API would relay the button state. If you don't mind you could ask AVM about further insights.

**Comment by andig** [comment]
Nevermind. The API does actually record the timestamp of last button press- so this should be possible.

**Comment by andig** [comment]
I would need a button though for testing. At this time I don't have a device available.

**Comment by marslyric** [comment]
I am able to send you the button.
Please give the possibility direct via -------@gmail.com.
Thanks in advance

**Comment by andig** [comment]
> I am able to send you the button.

Ist angekommen :) Habe derzeit noch einen hartnäckigen Bug in Arbeit, dann schaue ich mir das an.

**Comment by andig** [comment]
Ich hab mal einen ersten versuch gemacht, aber völlig ungetestet!

**Comment by marslyric** [comment]
Danke,
Ich muss mir erst mal einen neuen Taster besorgen.

**Comment by andig** [comment]
Ich würd ihn Dir ja wieder einpacken- aber erst müssten wir testen :O

**Comment by marslyric** [comment]
Ja, das ist sinnvoll;)
Hab schon zwei Neue bestellt.
Bitte behalte den Taster.

**Comment by andig** [comment]
Was mir noch auffällt: ein Button sind eigentlich 2- deren Namen sind über die FB konfigurierbar und werden hier als 2 unterschiedliche Buttons hinzu gefügt. Aktuell gilt das `display` Setting für beide, ggf. muss das noch differenziert werden.

**Comment by marslyric** [comment]
Der eine ist kurz drücken und der andere sollte länger drücken sein, wenn
ich das richtig verstanden habe.
