### ISSUE TITLE
2 Fritz Boxen und 1ne Config?

### ISSUE THREAD

**Issue by m4d-maNu** [andig/homebridge-fritz#72]
Hi,

ich habe 2 FritzBoxen, einmal noch eine 6490 cable und dann eine 7390. Die 6490 ist das Hauptgerät und die 7390 ist  via Kabel als Client verbunden. So erweitert sie mir nicht nur das Netzwerk (via LAN, WLAN und Gast WLAN) sondern erweitert mir auch mein Dect Signal.

Ist es irgendwie möglich, dass wenn ich dann das Gast WLAN über HomeKit abschalte, dass es auf beiden Geräten abgeschaltet wird?

**Comment by andig** [comment]
Nur wenn Homekit Dir das also Automatisierung bietet. Hier sind es unterschiedliche Geräte.

**Comment by m4d-maNu** [comment]
Das lässt sich relativ leicht einrichten. Denn ich hätte dann ja 2 Schalter und diese könnten einfach als Gruppe zusammen gefasst werden. Bleibt nur die Frage wie ich die Config entsprechend nun anpasse, damit das Plugin weiß das 2 Fritz Boxen verwendet werden. Ich könnte zwar nun relativ einfach eine weitere Instanz anlegen aber ich hätte gern die beiden FritzBoxen schon in meiner FritzBox Instanz.

**Comment by m4d-maNu** [comment]
Hat sich erledigt, an sich ja logisch wie nun die Plattform ein weiteres mal intrigiert wird.

```
"platforms": [{
		"platform": "Fritz!Box",
		"name": "1te FritzBox mit SmartHome Geräten",
		"username": "admin",
		"password": "xxxxxx",
		"url": "http://xxx.xxx.x.x",
		"interval": "60",
		"concurrent": false,
		"devices": {
			"wifi": {
				"name": "Gast Wlan 1te FritzBox",
				"display": true
			},
			"thermostat": {
				"ContactSensor": true
			}
		},
		"options": {
			"strictSSL": true
		}
	}, {
		"platform": "Fritz!Box",
		"name": "2te FritzBox nur für die Erweiterung von LAN, WLAN und Dect",
		"username": "admin",
		"password": "xxxx",
		"url": "http://xxx.xxx.xxx",
		"interval": "60",
		"concurrent": false,
		"devices": {
			"wifi": {
				"name": "GAST Wlan 2te FritzBox",
				"display": true
			}
		},
		"options": {
			"strictSSL": true
		}
	}]
```
