### ISSUE TITLE
Complete overview of possible settings

### ISSUE THREAD

**Issue by mike-lischke** [andig/homebridge-fritz#84]
This homebridge plugin is very useful, many thanks for writing it! It would be perfect, if there was a webpage/document that describes all possible settings in detail. The readme contains a few things and currently I'm using the example config. However, this is not really self-explanatory, so I would much appreciate some more documentation. Thanks.

**Comment by andig** [comment]
It seems you have been able to answer all your questions with the existing docs. What exactly is missing? Would you be interested in proposing a structure that improved documentation should follow? Happy to accept contributions!

**Comment by mike-lischke** [comment]
Yes, I could make it work, somehow... I'd prefer to know what I'm doing, however ;-)

I admit, there's already info for the most important setup, however it's a bit confusing for me. Questions came up like:

- What's the list of required options? I only scanned the list of optional settings and missed a few things, as I assumed this would not be interesting for the initial setup (e.g. the AIN reference).
- What's the URL used for?
- I see a difference in the device specification for an outlet, which I gave another name than "outlet-1" and it still shows up with that own name.
  - So, what name should I use in the configuration?
  - Does it even matter what name I use? How does the plugin know of what type the accessory is?
  - What if I have more than one outlet?
- Which accessories (devices) are supported at all?
- Are configuration keys case-sensitive?
- How can I configure the individual names of combined accessories? For instance my outlet has the plug and a temp sensor. Both appear under the plug's name, which is (especially on a small screen) hard to tell apart (ok, the icon helps a bit, but still).
- What is the "hidden-3" device? Would it be the same as "hidden-1" or just "hidden"? Does the attached number play a role somewhere?

`<nitpick>`The casing of the keys in a device is a bit odd, given that all others are lower case`</nitpick>`

Thanks, Mike

**Comment by andig** [comment]
OK, lets take this one by one. I have to assume you've read the README.

- What's the list of required options? 
Anything to make it work. If your FB is at the default address you only need user/password. This should be obvious?

- Which accessories (devices) are supported at all?
README:
```
WLAN guest access switch
Fritz!DECT outlets (200, 210)
Fritz!Powerline outlets (510, 540)
Fritz!DECT (300, 301) and Comet!DECT thermostats
Fritz!DECT repeaters as temperature sensor (100)
Window sensors including HAN FUN devices e.g. of Deutsche Telekom
```

Are you missing anything?

- What's the URL used for?
README:
```
url: Fritz!Box address
```

I'll answer the rest when I have some more time.
