### ISSUE TITLE
Batterystatus not pulled from API

### ISSUE THREAD

**Issue by GitMeHenk** [andig/homebridge-fritz#85]
The plugin failes to get the battery status, tested with an integration im using myself and the api call works so it must a be problem with the plugin.

See attached logging
![3702B8BA-1646-4A02-AB13-CC19715A2815](https://user-images.githubusercontent.com/52503571/66714677-e6e4d580-edb9-11e9-8ee8-95c60c3ba3bd.jpeg)

Correct api call is described in the AHA interface documentation. My hunch is that the info that “getdeviceinfos” returns isnt parsed correctly.

See attachment 2, “getdevicelistinfos” call.
![62DA8B14-55BD-4C52-90FB-7D55485A1739](https://user-images.githubusercontent.com/52503571/66714723-8e620800-edba-11e9-8c90-55a1aeff5d67.jpeg)

**Comment by andig** [comment]
You you provide a debug log? Does this happen all the time?

**Comment by GitMeHenk** [comment]
> You you provide a debug log? Does this happen all the time?

Hi Andig, im unable to run debug mode under hoobs at the moment , some hints there would be helpfull. And yes it happens all the time, never got a valid battery status from the thermostat devices (d301, laterst firmware) since i installed the plugin.

Did you see the attachment where it showed the log line?

**Comment by andig** [comment]
> Hi Andig, im unable to run debug mode under hoobs at the moment , some hints there would be helpfull. 

Please see readme. I would suspect- as battery requries screen scraping- that your UI is different. Could you share the HTML of the UI's battery page from your browser?
