### ISSUE TITLE
Keine Antwort in Home-App

### ISSUE THREAD

**Issue by jngmrks** [andig/homebridge-fritz#88]
Neues Problem mit der neuesten Software. Beim öffnen der App kommt bei allen Geräten keine Antwort. Problem: Timeout nach 10 Sekunden.
möglicher Hintergrund: Neuerdings werden alle Geräte abgefragt anstatt jedes einzeln, die Antwort aller Geräte dauert zu lange -> keine Antwort.
Klickt man einzelne Geräte an, wird der Status aktualisiert.

iOS 13.1.3 auf iPad, iPhone und Catalina 10.15 (19A602)

**Comment by Kai9555** [comment]
Moin, bei mir geht es ohne Probleme mit 13.1.3 und 10.15. Meine Einstellungen sind:

{
            "platform": "Fritz!Box",
            "name": "My FritzBox",
            "username": "admin",
            "password": "****",
            "url": "http://fritz.box",
            "interval": 1800,
            "concurrent": true,
            "devices": {
                "wifi": {
                    "name": "Guest WLAN",
                    "display": false
                }

**Comment by andig** [comment]
@jngmrks @Kai9555: welche Version?
@jngmrks: Debug log?

**Comment by Kai9555** [comment]
> @jngmrks @Kai9555: welche Version?
> @jngmrks: Debug log?

iOS 13.1.3 bzw. Mac OS 10.15 oder was meinst du?

**Comment by andig** [comment]
> oder was meinst du?

Ich meine die Version des Plugins, nicht des OS.

**Comment by Kai9555** [comment]
> > oder was meinst du?
> 
> Ich meine die Version des Plugins, nicht des OS.

homebridge-fritz v0.8.0

**Comment by jngmrks** [comment]
0.8.0 und im Log gar nichts zu sehen, da läuft alles ganz normal durch, nur die Rückmeldungen kommen erst nach dem Keine Antwort. Ab und zu kommt eine Rückmeldung früher durch, dann wird ein Thermostat oder Schalter angezeigt und alle anderen auf keine Antwort

**Comment by andig** [comment]
> 0.8.0 und im Log gar nichts zu sehen

Bitte nochmal ein Debuglog erzeugen in dem alle Aufrufe sichtbar sind

**Comment by jngmrks** [comment]
Ich trau mich gar nicht zu sagen wo der Fehler lag, aber ich hab ihn gefunden 😅. Ich hab mal alle Plugins ausser das Fritz deaktiviert und dann lief alles. Schritt für Schritt bis ich zum roomba-stv kam. Wenn der Staubsauger nicht in der Ladestation steht, dann Funktioniert die Home-App nicht mehr (da keine Antwort).
